### ISSUE TITLE
Multiple menu in this same location

### ISSUE THREAD

**Issue by NorraPL** [code4romania/cms#41]
In current version, if we setup a few menu in this same location, cms returned only first menu. 

I think it's wrong way - because cms should support multiple menu in this same place (like in Wordpress theme)

**Comment by NorraPL** [comment]
Your concepction doesn't work via multi_select input

**Comment by andreiio** [comment]
Hi @EPInformatyka,

This package is still in development and hasn't been released yet. We're not currently providing any support for it.
